FROM ubuntu:16.04
LABEL maintainer "Norbert Wenzel"
WORKDIR /numpy_data

RUN apt-get update && apt-get install -y \
        build-essential \
        clang \
        libboost-all-dev \
    && rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/bin/bjam /usr/bin/b2
RUN echo "using gcc : : : <cxxflags>-std=c++11 ;\nusing clang : : : <cxxflags>-std=c++11 ;" > ~/user-config.jam
COPY README.md /numpy_data/README.md
